version: '3.8'

services:
  php:
    image: php:8.2-apache
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_new_database
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3307:3306"  # Gunakan port 3307 di host
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
